CREATE DATABASE readme
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE readme;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL UNIQUE,
  avatar_path VARCHAR(255)
);

CREATE TABLE posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  quote_autor VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  video VARCHAR(255) NOT NULL,
  reference VARCHAR(255) NOT NULL,
  view_post INT,
  user_id INT,
  type_content_id INT
);

CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  content TEXT NOT NULL,
  user_id INT,
  post_id INT
);

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add DATETIME DEFAULT CURRENT_TIMESTAMP,
  content TEXT NOT NULL,
  user_id INT,
  autor_id1 INT
);

CREATE TABLE types_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_type VARCHAR(255) NOT NULL,
  name_class_icon VARCHAR(255) NOT NULL
);

CREATE TABLE likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  post_id INT
);

CREATE TABLE subscriptions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  autor_id1 INT
);

CREATE TABLE hashtags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_hashtag VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE posts_hashtags (
  post_id INT,
  hashtag_id INT
);
